'use strict';
/**
 * The adapter grid. See STRATA-GUIDE.md §3 and §6 step 3.
 *
 * A recall ships GENERIC logic that `requires` a port (e.g. an EntityStore exposing
 * `{findById, findByEmail, create}`). The brownfield tax was the model HAND-WRITING the code that binds
 * that port to the project's real data layer. This module generates that binding DETERMINISTICALLY from
 * the guide: given a domain + the datastore it is bound to, it emits a ready store adapter the recall can
 * import — the exact file oauth/securepw paid turns to write by hand.
 *
 * Two design rules:
 *   1. The adapter EXPOSES the port's method names (findById…), so the recall calls it unchanged.
 *   2. The datastore handle is passed IN (`createXStore(db)`), never constructed here — one client for
 *      the whole app, and it matches how recalls already accept a store.
 *
 * The grid is small on purpose (STRATA-GUIDE.md §3): ~3 store families × ~6 backends. This file starts
 * with EntityStore on the two backends the losing benchmark tasks needed — prisma and in-memory — and is
 * structured so a new backend is one `case`, not a new architecture.
 */

import { Domain, Datastore } from './guide.js';

export interface RenderedAdapter {
  /** Suggested filename, relative to the project's dataAccess dir. */
  filename: string;
  /** The adapter source. */
  code: string;
  /** The factory export the wiring calls, e.g. "createUserStore". */
  factory: string;
  /** INJECT notes for method kinds we could not derive — empty when fully generated. */
  gaps: string[];
}

/** A method the recall expects, parsed from a `storeInterface` signature like "findByEmail(email)". */
interface MethodSpec {
  /** The name the adapter must EXPOSE (the port's name). */
  exposed: string;
  kind: 'findById' | 'findByField' | 'create' | 'list' | 'update' | 'delete' | 'custom';
  field?: string;   // for findByField
}

// ─── public entry ───────────────────────────────────────────────────────────

/**
 * Render an EntityStore adapter binding `domain` to `datastore`. Returns null when we have no template
 * for the datastore's `via` — the caller then leaves the recall's own INJECT slot in place rather than
 * emitting a guess (a plausible-but-wrong store is the worst outcome; STRATA-GUIDE.md §3).
 */
export function renderEntityStore(domain: Domain, datastore: Datastore): RenderedAdapter | null {
  const methods = parseInterface(domain);
  const factory = `create${cap(domain.entity)}Store`;
  const idField = domain.idField ?? 'id';

  // CASE 2 — the project ALREADY has a store, under its own method names. `methodAliases` is the signal:
  // you only alias when mapping the port's names onto existing ones. Emit a thin wrapper that delegates
  // to the real store, so we adapt to existing code instead of generating a second, empty store beside
  // it. This is the heart of the brownfield fix: bind to what's there, don't duplicate it.
  if (domain.methodAliases && Object.keys(domain.methodAliases).length) {
    return wrapExistingStore(domain, factory);
  }

  const via = (datastore.via ?? datastore.kind ?? '').toLowerCase();
  let body: { lines: string[]; gaps: string[] };
  switch (via) {
    case 'prisma':
      body = prismaBody(domain, methods, idField);
      break;
    case 'in-memory':
    case 'module-array':
      body = inMemoryBody(methods, idField);
      break;
    default:
      return null;   // no template → caller keeps the INJECT slot
  }

  const header =
    `// Generated by Strata from strata.guide.json — EntityStore adapter for ${domain.entity} `
    + `on ${datastore.kind}${datastore.via ? ` (${datastore.via})` : ''}.\n`
    + `// Exposes the port interface the recall expects; pass your ${datastore.handle ?? 'store'} handle in.\n`;

  const code =
    header
    + `module.exports.${factory} = function (${handleParam(via, datastore)}) {\n`
    + body.lines.map(l => '  ' + l).join('\n') + '\n'
    + `};\n`;

  return { filename: `${domain.name}Store.js`, code, factory, gaps: body.gaps };
}

// ─── KeyValueStore family (SessionStore / IdempotencyStore / Cache / RateLimiterStore) ──────────
//
// Hybrid model (STRATA-GUIDE.md §3): these are DISTINCT ports in the guide (clear intent) but share ONE
// KV body per backend. The factory is named per port (createSessionStore, createIdempotencyStore…) so
// the wiring reads well; the implementation is identical. Canonical KV interface: get/set/del, with an
// optional ttl on set — the shape every session/idempotency/cache recall consumes.

/**
 * Render a KeyValueStore adapter for `port` (e.g. "SessionStore") backed by `datastore`. Returns null
 * for a backend we have no template for, so the caller keeps the recall's own INJECT slot.
 */
export function renderKeyValueStore(port: string, datastore: Datastore): RenderedAdapter | null {
  const factory = `create${cap(port)}`;
  const via = (datastore.via ?? datastore.kind ?? '').toLowerCase();

  let body: string[];
  let param: string;
  switch (via) {
    case 'redis':
    case 'ioredis':
    case 'node-redis':
      param = datastore.handle ?? 'redis';
      body = [
        `return {`,
        `  get: async (key) => { const v = await ${param}.get(key); return v == null ? null : JSON.parse(v); },`,
        `  set: async (key, value, ttlSeconds) => {`,
        `    const s = JSON.stringify(value);`,
        `    if (ttlSeconds) await ${param}.set(key, s, 'EX', ttlSeconds); else await ${param}.set(key, s);`,
        `  },`,
        `  del: async (key) => { await ${param}.del(key); },`,
        `};`,
      ];
      break;
    case 'in-memory':
    case 'module-array':
      param = '';
      body = [
        `const store = new Map(); // key -> { value, expiresAt }`,
        `return {`,
        `  get: async (key) => {`,
        `    const e = store.get(key);`,
        `    if (!e) return null;`,
        `    if (e.expiresAt && e.expiresAt < Date.now()) { store.delete(key); return null; }`,
        `    return e.value;`,
        `  },`,
        `  set: async (key, value, ttlSeconds) => {`,
        `    store.set(key, { value, expiresAt: ttlSeconds ? Date.now() + ttlSeconds * 1000 : null });`,
        `  },`,
        `  del: async (key) => { store.delete(key); },`,
        `};`,
      ];
      break;
    default:
      return null;
  }

  const code =
    `// Generated by Strata from strata.guide.json — ${port} (KeyValueStore) on ${datastore.kind}`
    + `${datastore.via ? ` (${datastore.via})` : ''}.\n`
    + `module.exports.${factory} = function (${param}) {\n`
    + body.map(l => '  ' + l).join('\n') + '\n'
    + `};\n`;

  return { filename: `${lowerFirst(port)}.js`, code, factory, gaps: [] };
}

// ─── case 2: wrap an existing project store ─────────────────────────────────────

/**
 * Emit `create<Entity>Store(existing)` that exposes the port's method names but forwards each call to the
 * project's real store method (from `methodAliases`). No datastore template needed — we don't touch the
 * data layer, we just rename the surface the recall sees onto the surface the project already has.
 */
function wrapExistingStore(domain: Domain, factory: string): RenderedAdapter {
  const aliases = domain.methodAliases ?? {};   // portName -> projectMethodName
  const lines = Object.entries(aliases).map(
    ([port, projectMethod]) => `  ${port}: (...args) => existing.${projectMethod}(...args),`,
  );
  const code =
    `// Generated by Strata from strata.guide.json — EntityStore wrapper for ${domain.entity}.\n`
    + `// Forwards the port's method names to your existing ${domain.store ?? 'store'}; pass it in.\n`
    + `module.exports.${factory} = function (existing) {\n`
    + `  return {\n${lines.join('\n')}\n  };\n`
    + `};\n`;
  return { filename: `${domain.name}Store.js`, code, factory, gaps: [] };
}

// ─── backend bodies ───────────────────────────────────────────────────────────

function prismaBody(domain: Domain, methods: MethodSpec[], idField: string): { lines: string[]; gaps: string[] } {
  // Prisma exposes each model as a lowercase-first accessor: prisma.user, prisma.orderItem.
  const model = lowerFirst(domain.collection ?? domain.entity);
  const gaps: string[] = [];
  const impl = (m: MethodSpec): string => {
    switch (m.kind) {
      case 'findById':    return `${m.exposed}: (id) => db.${model}.findUnique({ where: { ${idField}: id } }),`;
      case 'findByField': return `${m.exposed}: (${m.field}) => db.${model}.findUnique({ where: { ${m.field} } }),`;
      case 'create':      return `${m.exposed}: (data) => db.${model}.create({ data }),`;
      case 'list':        return `${m.exposed}: (opts = {}) => db.${model}.findMany(opts),`;
      case 'update':      return `${m.exposed}: (id, data) => db.${model}.update({ where: { ${idField}: id }, data }),`;
      case 'delete':      return `${m.exposed}: (id) => db.${model}.delete({ where: { ${idField}: id } }),`;
      default:
        gaps.push(`${domain.name}Store.${m.exposed}`);
        return `${m.exposed}: () => { throw new Error('INJECT: implement ${m.exposed} for ${domain.entity}'); },`;
    }
  };
  return { lines: ['return {', ...methods.map(m => '  ' + impl(m)), '};'], gaps };
}

function inMemoryBody(methods: MethodSpec[], idField: string): { lines: string[]; gaps: string[] } {
  const gaps: string[] = [];
  const impl = (m: MethodSpec): string => {
    switch (m.kind) {
      case 'findById':    return `${m.exposed}: async (id) => rows.get(id) || null,`;
      case 'findByField': return `${m.exposed}: async (${m.field}) => [...rows.values()].find(r => r.${m.field} === ${m.field}) || null,`;
      case 'create':      return `${m.exposed}: async (data) => { const id = data.${idField} ?? String(++seq); const row = { ...data, ${idField}: id }; rows.set(id, row); return row; },`;
      case 'list':        return `${m.exposed}: async () => [...rows.values()],`;
      case 'update':      return `${m.exposed}: async (id, data) => { const row = { ...rows.get(id), ...data, ${idField}: id }; rows.set(id, row); return row; },`;
      case 'delete':      return `${m.exposed}: async (id) => { rows.delete(id); },`;
      default:
        gaps.push(m.exposed);
        return `${m.exposed}: async () => { throw new Error('INJECT: implement ${m.exposed}'); },`;
    }
  };
  return {
    lines: ['const rows = new Map();', 'let seq = 0;', 'return {', ...methods.map(m => '  ' + impl(m)), '};'],
    gaps,
  };
}

/** in-memory needs no injected handle; datastore-backed adapters take the project's client. */
function handleParam(via: string, datastore: Datastore): string {
  if (via === 'in-memory' || via === 'module-array') return '';
  return datastore.handle ?? 'db';
}

// ─── interface parsing ─────────────────────────────────────────────────────────

/**
 * Turn a domain's `storeInterface` into method specs. Falls back to the canonical EntityStore trio when
 * none is declared, so an entity with no explicit interface still gets a usable store. `methodAliases`
 * are respected: the EXPOSED name stays the port name (the recall calls `findById`), but a project that
 * named the same operation `getById` is recognised so the KIND is derived from the canonical name.
 */
function parseInterface(domain: Domain): MethodSpec[] {
  const sigs = (domain.storeInterface && domain.storeInterface.length)
    ? domain.storeInterface
    : ['findById(id)', 'findByEmail(email)', 'create(data)'];

  // Reverse the alias map: projectName -> portName, so a signature written in the project's vocabulary
  // still classifies by its canonical port meaning.
  const toPort: Record<string, string> = {};
  for (const [port, project] of Object.entries(domain.methodAliases ?? {})) toPort[project] = port;

  return sigs.map(sig => {
    const name = sig.replace(/\(.*/, '').trim();
    const canonical = toPort[name] ?? name;   // classify by the port name when this is an alias
    const exposed = toPort[name] ?? name;     // expose the port name to the recall
    return { exposed, ...classify(canonical) };
  });
}

function classify(name: string): { kind: MethodSpec['kind']; field?: string } {
  if (/^findById$/i.test(name) || /^getById$/i.test(name)) return { kind: 'findById' };
  const byField = name.match(/^(?:find|get)By([A-Z]\w*)$/);
  if (byField) return { kind: 'findByField', field: lowerFirst(byField[1]) };
  if (/^(create|insert|add)$/i.test(name)) return { kind: 'create' };
  if (/^(list|findAll|getAll|all)$/i.test(name)) return { kind: 'list' };
  if (/^(update|patch|edit)$/i.test(name)) return { kind: 'update' };
  if (/^(delete|remove|destroy)$/i.test(name)) return { kind: 'delete' };
  return { kind: 'custom' };
}

// ─── tiny string helpers ───────────────────────────────────────────────────────

function cap(s: string): string { return s.charAt(0).toUpperCase() + s.slice(1); }
function lowerFirst(s: string): string { return s.charAt(0).toLowerCase() + s.slice(1); }
