/**
 * Generate endpoints from a guide's DECLARED operations.
 *
 * THE GAP THIS CLOSES. Strata's cost win tracks one variable, measured across three tasks: whether a
 * delivered recall owns the endpoint the work is about.
 *
 *   catalog      api.pagination.v1 owns GET /products          0.40x cost, 100% quality
 *   stripejune   payment.stripe-webhook.v1 owns its route      0.77x cost, 100% quality
 *   idempotency  nothing owns a route — all decorators         1.75x cost,  57% quality
 *
 * A decorator with no host is guarding nothing. On the idempotency task the session had to invent the
 * orders API itself — 127, 37 and 51 lines across three runs, a different design each time — and one
 * mismatch in it collapsed five of seven graded checks, because they all depended on being able to
 * create an order at all.
 *
 * Recalls cannot own that endpoint: what an order IS is business logic, and no library can hold it in
 * advance. But a GUIDE can, because the developer (or the model, once) wrote it down. So the endpoint
 * comes from the declaration, and the decorators compose onto it exactly as they compose onto
 * pagination's route today.
 *
 * WHAT THIS GENERATES AND WHAT IT REFUSES TO. It writes the endpoint, its store, and its wiring —
 * the mechanical parts, derivable from the declared fields. It does NOT invent business rules: an
 * operation whose semantics are not derivable from its method and path gets a real handler with a
 * named INJECT slot, not a guess. Guessing there would be the same failure as guessing an entity —
 * code that compiles, boots, passes a smoke test, and is quietly wrong.
 */
import { StrataGuide, Domain, DomainOperation } from './guide.js';

export interface GuideRouteResult {
  /** Route code for the wiring template's {{ROUTES}} slot. */
  code: string;
  /** Require lines the wiring needs, already relative to the wiring module. */
  requires: string[];
  /** Files to write into the project (the generated store). */
  files: { rel: string; source: string }[];
  /** Operations that produced an endpoint, e.g. "Order.createOrder (POST /orders)". */
  built: string[];
  /** Declared operations deliberately NOT built, with the reason. */
  skipped: string[];
}

const EMPTY: GuideRouteResult = { code: '', requires: [], files: [], built: [], skipped: [] };

function parseRoute(route?: string): { method: string; path: string } | null {
  if (!route) return null;
  const m = route.trim().match(/^(GET|POST|PUT|PATCH|DELETE)\s+(\/\S*)$/i);
  return m ? { method: m[1].toUpperCase(), path: m[2] } : null;
}

const camel = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

/**
 * What KIND of operation is this, from its method and path alone?
 *
 * Deliberately shallow. The four shapes below are the ones whose semantics HTTP itself defines, so
 * generating them is transcription rather than invention. Anything else — /cancel, /approve, /refund —
 * carries meaning only the author knows, and gets a slot.
 */
type Kind = 'create' | 'list' | 'read' | 'update' | 'delete' | 'custom';
function kindOf(method: string, p: string): Kind {
  const hasParam = /:\w+/.test(p);
  const trailing = p.split('/').filter(Boolean).pop() ?? '';
  const verbSuffix = hasParam && !/^:\w+$/.test(trailing);
  if (verbSuffix) return 'custom';
  if (method === 'POST' && !hasParam) return 'create';
  if (method === 'GET' && !hasParam) return 'list';
  if (method === 'GET') return 'read';
  if (method === 'PUT' || method === 'PATCH') return 'update';
  if (method === 'DELETE') return 'delete';
  return 'custom';
}

/** The in-memory store backing a domain the project does not have a table for. */
function storeSource(domain: Domain): string {
  const id = domain.idField ?? 'id';
  const writable = (domain.fields ?? []).filter(f => !f.isId && !f.generated).map(f => f.name);
  return `'use strict';
/**
 * Generated by Strata from strata.guide.json — in-memory store for ${domain.entity}.
 *
 * The guide declares this domain with "exists": false, so the project has no table for it yet. This is
 * a real, working store, not a stub — but it does NOT survive a restart. Point it at your database
 * when you have one; the route above only uses the four methods below.
 */
let seq = 1;
const rows = [];

const WRITABLE = ${JSON.stringify(writable)};

function pick(input) {
  const out = {};
  for (const k of WRITABLE) if (input && input[k] !== undefined) out[k] = input[k];
  return out;
}

function create(input) {
  const row = Object.assign({ ${id}: seq++ }, pick(input), { createdAt: new Date().toISOString() });
  rows.push(row);
  return row;
}

function list() {
  return rows.slice().reverse();
}

function get(id) {
  return rows.find((r) => String(r.${id}) === String(id)) || null;
}

function update(id, patch) {
  const row = get(id);
  if (!row) return null;
  Object.assign(row, pick(patch));
  return row;
}

module.exports = { create, list, get, update };
`;
}

/** A validation schema literal derived from the declared fields, for the create/update handlers. */
function schemaLiteral(domain: Domain): string {
  const entries = (domain.fields ?? [])
    .filter(f => !f.isId && !f.generated)
    .map(f => {
      const t = f.type === 'enum' ? 'string' : f.type;
      const parts = [`type: '${t}'`];
      if (f.required) parts.push('required: true');
      if (f.enumValues?.length) parts.push(`enum: ${JSON.stringify(f.enumValues)}`);
      return `    ${f.name}: { ${parts.join(', ')} },`;
    });
  return `{\n${entries.join('\n')}\n  }`;
}

function handlerFor(kind: Kind, domain: Domain, op: DomainOperation, r: { method: string; path: string }, store: string): string {
  const id = domain.idField ?? 'id';
  const notFound = `      if (!row) return res.status(404).json({ error: '${domain.entity} not found' });`;

  switch (kind) {
    case 'create':
      return `      const created = ${store}.create(req.body || {});
      res.status(201).json(created);`;
    case 'list':
      return `      res.json({ data: ${store}.list() });`;
    case 'read':
      return `      const row = ${store}.get(req.params.${id});
${notFound}
      res.json(row);`;
    case 'update':
      return `      const row = ${store}.update(req.params.${id}, req.body || {});
${notFound}
      res.json(row);`;
    case 'delete':
      return `      const row = ${store}.get(req.params.${id});
${notFound}
      res.status(204).end();`;
    default:
      // A custom verb carries meaning only the author knows. Generate the endpoint, load the record,
      // and stop — the rule itself is a named slot, never a guess.
      return `      const row = ${store}.get(req.params.${id});
${notFound}
      // INJECT: apply the rule for "${op.name}"${op.guarantees ? ` — the guide declares: ${op.guarantees.replace(/\s+/g, ' ').slice(0, 120)}` : ''}
      res.json(row);`;
  }
}

/**
 * Build endpoints for ONE domain — the one the task resolved to.
 *
 * Scoping is by domain, not by operation. A guide may declare a dozen domains, and building all of
 * them on every call would generate an application nobody asked for; but within the domain the task is
 * about, every declared operation is built, because choosing a subset means re-guessing intent from
 * the task string — the exact heuristic the guide exists to replace. Every built operation also gets a
 * verifier check, so over-generation is visible and proven rather than silent.
 */
export function routesFromGuide(
  guide: StrataGuide | null,
  entityName: string | null,
  opts: { sourceRoot: string; hasValidation: boolean },
): GuideRouteResult {
  if (!guide?.domains?.length || !entityName) return EMPTY;
  const domain = guide.domains.find(d => d.entity === entityName);
  if (!domain) return EMPTY;

  const ops = (domain.operations ?? []).filter(o => parseRoute(o.route));
  if (!ops.length) return EMPTY;

  const store = `${camel(domain.entity)}Store`;
  const storeRel = `data/${store}.js`;
  const built: string[] = [];
  const skipped: string[] = [];
  const blocks: string[] = [];

  // Only generate a store for a domain the project does not have. A domain with exists:true already
  // has a home, and writing a second one would quietly fork its data.
  const needsStore = domain.exists === false;
  if (!needsStore) {
    skipped.push(`${domain.entity} store — the guide says this domain already exists; routes bind to your existing data layer`);
  }

  for (const op of ops) {
    const r = parseRoute(op.route)!;
    const kind = kindOf(r.method, r.path);
    const validate = opts.hasValidation && (kind === 'create' || kind === 'update')
      ? `validateRequest(${schemaLiteral(domain)}), `
      : '';
    blocks.push(`// ${domain.entity}.${op.name} — declared in strata.guide.json${op.guarantees ? `\n// guarantees: ${op.guarantees.replace(/\s+/g, ' ')}` : ''}
app.${r.method.toLowerCase()}(
  '${r.path}',
  ${validate}async (req, res, next) => {
    try {
${handlerFor(kind, domain, op, r, needsStore ? store : store)}
    } catch (err) {
      next(err);
    }
  },
);`);
    built.push(`${domain.entity}.${op.name} (${r.method} ${r.path})`);
  }

  const files = needsStore ? [{ rel: `${opts.sourceRoot ? opts.sourceRoot + '/' : ''}${storeRel}`, source: storeSource(domain) }] : [];
  const requires = [`const ${store} = require('./${storeRel.replace(/\.js$/, '')}');`];

  return { code: blocks.join('\n\n'), requires, files, built, skipped };
}
