/**
 * Generate endpoints from a guide's DECLARED operations.
 *
 * THE GAP THIS CLOSES. Strata's cost win tracks one variable, measured across three tasks: whether a
 * delivered recall owns the endpoint the work is about.
 *
 *   catalog      api.pagination.v1 owns GET /products          0.40x cost, 100% quality
 *   stripejune   payment.stripe-webhook.v1 owns its route      0.77x cost, 100% quality
 *   idempotency  nothing owns a route — all decorators         1.75x cost,  57% quality
 *
 * A decorator with no host is guarding nothing. On the idempotency task the session had to invent the
 * orders API itself — 127, 37 and 51 lines across three runs, a different design each time — and one
 * mismatch in it collapsed five of seven graded checks, because they all depended on being able to
 * create an order at all.
 *
 * Recalls cannot own that endpoint: what an order IS is business logic, and no library can hold it in
 * advance. But a GUIDE can, because the developer (or the model, once) wrote it down. So the endpoint
 * comes from the declaration, and the decorators compose onto it exactly as they compose onto
 * pagination's route today.
 *
 * WHAT THIS GENERATES AND WHAT IT REFUSES TO. It writes the endpoint, its store, and its wiring —
 * the mechanical parts, derivable from the declared fields. It does NOT invent business rules: an
 * operation whose semantics are not derivable from its method and path gets a real handler with a
 * named INJECT slot, not a guess. Guessing there would be the same failure as guessing an entity —
 * code that compiles, boots, passes a smoke test, and is quietly wrong.
 */
import { StrataGuide, Domain, DomainOperation } from './guide.js';
import { resolveKind, sampleBody, camel, Route } from './guide-kinds.js';

export interface GuideRouteResult {
  /** Route code for the wiring template's {{ROUTES}} slot. */
  code: string;
  /** Require lines the wiring needs, already relative to the wiring module. */
  requires: string[];
  /** Files to write into the project (the generated store). */
  files: { rel: string; source: string }[];
  /** Operations that produced an endpoint, e.g. "Order.createOrder (POST /orders)". */
  built: string[];
  /** Declared operations deliberately NOT built, with the reason. */
  skipped: string[];
}

const EMPTY: GuideRouteResult = { code: '', requires: [], files: [], built: [], skipped: [] };

function parseRoute(route?: string): { method: string; path: string } | null {
  if (!route) return null;
  const m = route.trim().match(/^(GET|POST|PUT|PATCH|DELETE)\s+(\/\S*)$/i);
  return m ? { method: m[1].toUpperCase(), path: m[2] } : null;
}

/**
 * The initial value of every field a new record does not carry.
 *
 * Only two sources, both cheap to justify: an explicitly declared `default`, and — for an enum — its
 * first member. Nothing else is invented; a string or number without a default simply stays absent.
 */
function initialValues(domain: Domain): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const f of domain.fields ?? []) {
    if (f.isId || f.generated) continue;
    if (f.default !== undefined) { out[f.name] = f.default; continue; }
    if (f.type === 'enum' && f.enumValues?.length) out[f.name] = f.enumValues[0];
  }
  return out;
}

/** The in-memory store backing a domain the project does not have a table for. */
function storeSource(domain: Domain): string {
  const id = domain.idField ?? 'id';
  const writable = (domain.fields ?? []).filter(f => !f.isId && !f.generated).map(f => f.name);
  return `'use strict';
/**
 * Generated by Strata from strata.guide.json — in-memory store for ${domain.entity}.
 *
 * The guide declares this domain with "exists": false, so the project has no table for it yet. This is
 * a real, working store, not a stub — but it does NOT survive a restart. Point it at your database
 * when you have one; the route above only uses the four methods below.
 */
let seq = 1;
const rows = [];

const WRITABLE = ${JSON.stringify(writable)};

function pick(input) {
  const out = {};
  for (const k of WRITABLE) if (input && input[k] !== undefined) out[k] = input[k];
  return out;
}

// Values a new record starts with. Declared defaults first; failing that, an enum field starts at its
// FIRST member, which is how lifecycles are conventionally written (pending/paid/cancelled,
// building/ready/promoted). Without this a record is created with no state at all, and every declared
// transition refuses it — a 409 that looks like a business rule and is really a missing initial value.
const DEFAULTS = ${JSON.stringify(initialValues(domain))};

function create(input) {
  const row = Object.assign({ ${id}: seq++ }, DEFAULTS, pick(input), { createdAt: new Date().toISOString() });
  rows.push(row);
  return row;
}

function list() {
  return rows.slice().reverse();
}

function get(id) {
  return rows.find((r) => String(r.${id}) === String(id)) || null;
}

function update(id, patch) {
  const row = get(id);
  if (!row) return null;
  Object.assign(row, pick(patch));
  return row;
}

function remove(id) {
  const i = rows.findIndex((r) => String(r.${id}) === String(id));
  if (i === -1) return false;
  rows.splice(i, 1);
  return true;
}

module.exports = { create, list, get, update, remove };
`;
}

/** A validation schema literal derived from the declared fields, for the create/update handlers. */
function schemaLiteral(domain: Domain): string {
  const entries = (domain.fields ?? [])
    .filter(f => !f.isId && !f.generated)
    .map(f => {
      const t = f.type === 'enum' ? 'string' : f.type;
      const parts = [`type: '${t}'`];
      if (f.required) parts.push('required: true');
      if (f.enumValues?.length) parts.push(`enum: ${JSON.stringify(f.enumValues)}`);
      return `    ${f.name}: { ${parts.join(', ')} },`;
    });
  return `{\n${entries.join('\n')}\n  }`;
}

/**
 * Build endpoints for ONE domain — the one the task resolved to.
 *
 * Scoping is by domain, not by operation. A guide may declare a dozen domains, and building all of
 * them on every call would generate an application nobody asked for; but within the domain the task is
 * about, every declared operation is built, because choosing a subset means re-guessing intent from
 * the task string — the exact heuristic the guide exists to replace. Every built operation also gets a
 * verifier check, so over-generation is visible and proven rather than silent.
 */
export function routesFromGuide(
  guide: StrataGuide | null,
  entityName: string | null,
  opts: { sourceRoot: string; hasValidation: boolean },
): GuideRouteResult {
  if (!guide?.domains?.length || !entityName) return EMPTY;
  const domain = guide.domains.find(d => d.entity === entityName);
  if (!domain) return EMPTY;

  const ops = (domain.operations ?? []).filter(o => parseRoute(o.route));
  if (!ops.length) return EMPTY;

  const store = `${camel(domain.entity)}Store`;
  const storeRel = `data/${store}.js`;
  const built: string[] = [];
  const skipped: string[] = [];
  const blocks: string[] = [];

  // Only generate a store for a domain the project does not have. A domain with exists:true already
  // has a home, and writing a second one would quietly fork its data.
  const needsStore = domain.exists === false;
  if (!needsStore) {
    skipped.push(`${domain.entity} store — the guide says this domain already exists; routes bind to your existing data layer`);
  }

  for (const op of ops) {
    const r = parseRoute(op.route)! as Route;
    // The registry decides what this operation IS. guide-routes no longer knows about kinds at all —
    // adding the next one must never mean editing this loop.
    const { kind, meta } = resolveKind(domain, op, r);
    const ctx = { domain, op, route: r, store, idField: domain.idField ?? 'id', meta };
    const validate = opts.hasValidation && (kind.id === 'create' || kind.id === 'update')
      ? `validateRequest(${schemaLiteral(domain)}), `
      : '';
    blocks.push(`// ${domain.entity}.${op.name} — declared in strata.guide.json (kind: ${kind.id})${op.guarantees ? `\n// guarantees: ${op.guarantees.replace(/\s+/g, ' ')}` : ''}
app.${r.method.toLowerCase()}(
  '${r.path}',
  ${validate}async (req, res, next) => {
    try {
${kind.handler(ctx)}
    } catch (err) {
      next(err);
    }
  },
);`);
    built.push(`${domain.entity}.${op.name} (${r.method} ${r.path}) [${kind.id}]`);
  }

  const files = needsStore ? [{ rel: `${opts.sourceRoot ? opts.sourceRoot + '/' : ''}${storeRel}`, source: storeSource(domain) }] : [];
  const requires = [`const ${store} = require('./${storeRel.replace(/\.js$/, '')}');`];

  return { code: blocks.join('\n\n'), requires, files, built, skipped };
}
